require: rubocop-rspec

inherit_gem:
  rubocop-github:
    - "config/default.yml"
  rubocop-rspec:
    - "config/default.yml"

AllCops:
  SuggestExtensions: false

Layout/LineLength:
  Enabled: true
  Max: 80
  AllowedPatterns:
    - '^\s*#'
  Exclude:
    - "*.gemspec"

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Max: 20
